[versions]
android-gradle-plugin = "9.0.0"
jgit = "7.5.0.202512021534-r"

[libraries]
jgit = { group = "org.eclipse.jgit", name = "org.eclipse.jgit", version.ref = "jgit" }
jgit-archive = { group = "org.eclipse.jgit", name = "org.eclipse.jgit.archive", version.ref = "jgit" }

[plugins]
android-application = { id = "com.android.application", version.ref = "android-gradle-plugin" }
